### ISSUE TITLE
"Edit Profile" link on the profile page is incorrect

### ISSUE THREAD

**Issue by ladyofthelog** [c-e-p/ourchive#31]
The "edit" button on https://ourchive-dev.stopthatimp.net/username/verity_test/ sends me to "https://ourchive-dev.stopthatimp.net/username/verity_test/ourchive-dev.stopthatimp.net/username/verity_test/edit"

**Comment by c-e-p** [comment]
Root cause: I'm not sure why this is happening but rendering URLs with root is broken on works/users. It definitely wasn't broken before. My guess is I may have inadvertently changed something about how the parent-level template renders that breaks the links.

It is a pain, but I simply removed them to be relative links. And now this is resolved.
