### ISSUE TITLE
Error when trying to create new work

### ISSUE THREAD

**Issue by ladyofthelog** [c-e-p/ourchive#32]
<img width="458" alt="Screen Shot 2023-05-26 at 1 14 58 AM" src="https://github.com/c-e-p/ourchive/assets/46003573/b74c0d22-51a1-4851-9c0f-98c0dbe1e6ee">

I get this error when attempting to create a new work. UBlock is disabled, I confirmed in the admin panel that I should have the power to add a new work, and I am using Chrome Version 113.0.5672.92.

I also think popping up from the lower right of this screen is a weird place to put this error message...

**Comment by c-e-p** [comment]
This (and most of the other issues you sent I believe) is related to the way DRF handles URLs under a reverse proxy with Django auth (rather than Token auth). Worst case scenario is we implement token auth right now -- which I don't want to do -- but I'm hoping to find a fix with some middleware today.

**Comment by c-e-p** [comment]
Root cause: some issues with NGINX proxy forwarding and a need to set origin on the head when using requests in the frontend view. This is resolved.
