### ISSUE TITLE
"Bookmark" link from work is incorrect

### ISSUE THREAD

**Issue by ladyofthelog** [c-e-p/ourchive#33]
When I tried to bookmark the lone work on this site @ https://ourchive-dev.stopthatimp.net/works/1/, it took me to "https://ourchive-dev.stopthatimp.net/works/1/ourchive-dev.stopthatimp.net/bookmarks/new/1"

**Comment by c-e-p** [comment]
same deal as the others. previous note:

Root cause: I'm not sure why this is happening but rendering URLs with root is broken on works/users. It definitely wasn't broken before. My guess is I may have inadvertently changed something about how the parent-level template renders that breaks the links.

It is a pain, but I simply removed them to be relative links. And now this is resolved.
