### ISSUE TITLE
Empty User Works Page gives 500 Error

### ISSUE THREAD

**Issue by ladyofthelog** [c-e-p/ourchive#35]
https://ourchive-dev.stopthatimp.net/username/lost/ returns user lost's works page!

https://ourchive-dev.stopthatimp.net/username/verity_test/ returns a 500 error

**Comment by ladyofthelog** [comment]
Now it's not returning a 500 error but I don't know why. I did screencap the earlier error tho ( @ 1:25am EST)
<img width="654" alt="Screen Shot 2023-05-26 at 1 25 46 AM" src="https://github.com/c-e-p/ourchive/assets/46003573/bd345e08-f1d1-40af-8b4f-1e1cd83cb5e0">

**Comment by c-e-p** [comment]
Pretty sure this was related to issues we were having with the URL parsing and proxying. This should be resolved. If it comes up again pls let me know the nav path as it might be related to where you were prior to being on this page...but it's more likely it was nginx config stuff that I've since resolved.
