### ISSUE TITLE
AO3 Work Import

### ISSUE THREAD

**Issue by ladyofthelog** [c-e-p/ourchive#49]
Currently, there is no import feature available. This will be a barrier for some users to migrating to ourchive instances.

[AO3 downloader](https://nianeyna.dev/ao3downloader) is one option. [My fork of ao3 scraper](https://github.com/ladyofthelog/ao3) might also have some helpful code to glean, including for comment scraping.

Locked works may not be able to be imported by the import tool. Workaround: ask users to mass or individually unlock and re-lock works if needed.

**Comment by Candleja** [comment]
wait, locked works are only archive-locked, not _private_ the way bookmarks or friendslocked livejournal entries are. any registered account can see them.

new workaround proposal: 
a config option that lets the instance owner embed credentials (cookie or password, whatever) for an ao3 account

the import feature should just log in as the configured ao3 account owned by the ourchive owner and get access like that

(and by "ao3 account owned by the ourchive owner" i mean "they would just make a new empty account to be exclusively used by the ourchive instance, not reuse their existing human-owned one")

**Comment by Candleja** [comment]
Also, this is silly but the way video game guilds work online for one-time identity verification of a user between Website A and Website B is:

"Put this token into your profile on Website A to prove that you're person A"

So that's something that _could_ be included as a "make it slightly harder to bulk import someone else's works into your account" guardrail, if desired, but I don't really think it's important for MVP (or at all?) since if someone actually wanted to impersonate or plagiarize someone else they could just do it by hand, and either way the solution would end up being "a human moderator looks at you and says 'lol you cant do that get out'"

I don't think it'd actually matter from a practical standpoint, but I guess it could make users feel more secure if they have to "do something" to allow an import, in the same way that putting a picture of the visa logo on a checkout page makes users feel more secure.

**Comment by ladyofthelog** [comment]
I like the "use configured account" idea, maybe with an option to omit this step with the flag that this will only import public works.
