### ISSUE TITLE
Work Exchanges

### ISSUE THREAD

**Issue by c-e-p** [c-e-p/ourchive#55]
* Cowriting
* Countdown

Candle: an exchange/challenge interface that integrated the concept of deadline dates (eg: the signup time limit, assignments, reveals, the other parts, etc.) i think could be nice
like imagine a scenario where you could browse "exchanges in this fandom that are open for signups", "exchanges in this fandom that have already completed", etc.

**Comment by Candleja** [comment]
**As a non-participating reader:**

I would like to be able to browse and search Work Exchanges that might interest me, based on their fandom, tags, or status ("has posted works, has revealed works, is open to participants").

I would like to see the planned schedule for an Exchange, so that I can know when to come back if it's incomplete (and also know at a glance if it's already finished).

I would like to subscribe to an Exchange as a non-participant and be notified when something I care about happens (such as works being posted/revealed).

I would like to be able to bookmark an entire exchange. (Maybe?)



**As a participant:**

I would like to affiliate my account with an exchange even before I have a work ready to post.

I would like to receive notifications and communications from the exchange moderators, whenever they deem it necessary.

I would like to opt-out of notifications from the exchange mods, if I find them really annoying and don't want to listen to them.

I would not want my account's email address to be made visible to non-admin users on the site.

I would want an easy place where I can review the exchange's core features/settings as chosen by the mod (eg: will you be assigned a recipient or is this more a generalized fest? are there prompts to fill, or no? if someone defaults are there pinch hits? is there a late submission/extension policy? is there a minimum word count for fic?)

**Comment by Candleja** [comment]
For participants there's probably a bunch of considerations around anonymity to take into account -- what can be done anonymously, what can be done anonymously only with mod settings permission, what mods can see or do even when you're anonymous

**Comment by Candleja** [comment]
As an exchange runner...

I think I would want some sort of way to connect reoccurring exchanges to each other. If I run FicFest 2020, I want FicFest 2021 to be affiliated with it somehow.


Which then leads to, as a reader:

If an exchange happens every year, I want it to be easy for me to navigate to the exchange's works for the next year (or the previous year).

I think I would also want to be able to search for anything scoped within "This Exchange", even if it includes looking at previous years' works.
