### ISSUE TITLE
Work Anthologies

### ISSUE THREAD

**Issue by c-e-p** [c-e-p/ourchive#56]
* Support for series (give flexible object labeling that overrides default UI so "x anthology" becomes "The Fast Saga"??)
* Support for multi-author
* Add markdown edit support

**Comment by Candleja** [comment]
As an author:

I want to collect different bundles of my related works into single viewable places, but I also want to be able to specify the difference between an anthology or a series ("a collection of my faves" vs "these works are all set in the same universe and directly relate to each other, read them in order"), so as to not confuse my readers.

I want to be able to put my works into multiple anthologies (a single work should be able to be part of "The Fast Saga", "My Fave Action Fics", and "Kinktober 2020" at the same time).


As a reader:

When I view an anthology, I want to be able to look at tags (or other info provided by the author) to quickly determine if there is something inside it that I want to read, and also, where that thing is. 

I want to be able to bookmark an individual part of an anthology, rather than the entire thing.
